### ISSUE TITLE
eliminate dependency on nokogiri

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#125]
would make installation easier (i.e. should not then require a compiler / development toolchain)

**Comment by aelkiss** [comment]
Could use REXML instead?

**Comment by billdueber** [comment]
Can probably do this using [oga](https://github.com/YorickPeterse/oga. That will still require native extensions, which means either a compiler or the jruby version, but has the advantage of not needing the whole enormous build-in-our-own-libxml thing nokogiri has going on. 

REXML is ... dirty, but I guess it works. I can take a look at this if you'd like.

**Comment by aelkiss** [comment]
The XML needs here are pretty minimal, so I'd like to try REXML and see if it meets the needs - feedback from partners is that minimizing dependencies is pretty important if they're going to use this.

**Comment by aelkiss** [comment]
Migrated to HTREPO-122
