### ISSUE TITLE
error if OCR or coordinate OCR is not UTF-8

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#19]

**Comment by grosscol** [comment]
For XML, there is a specification for explicitly stating the encoding.  I'm thinking SAX parser, read attributes of first non-comment element.  Check that encoding is set properly there, or error.

For plain text, determining if a string of bytes is valid utf-8 seems like a difficult problem:
http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt has some examples of things that can be tested to conclusively say, "this is not valid utf-8."  Sections 3 and 5 seem like that are what we'd end up implementing checks for using raw byte matching.

**Comment by aelkiss** [comment]
The coordinate OCR isn't required to be valid XML (although we should certainly warn if it isn't), so we can't completely rely on that.

The approach the existing validator takes is to load the file as raw bytes, try to decode it as UTF-8, and catch any exceptions. I'm sure we can do it more elegantly in Ruby:

```perl
sub _validate_utf8 {
    my $self       = shift;
    my $volume     = $self->{volume};
    my $utf8_files = $volume->get_utf8_files();
    my $path       = $volume->get_staging_directory();

    foreach my $utf8_file (@$utf8_files) {
        eval {
            my $utf8_fh;
            open( $utf8_fh, "<", "$path/$utf8_file" )
                or croak("Can't open $utf8_file: $!");
            local $/ = undef;    # turn on slurp mode
            binmode( $utf8_fh, ":bytes" )
            ;                  # ensure we're really reading it as bytes
            my $utf8_contents = <$utf8_fh>;
            my $decoded_utf8 =
            decode( "utf-8-strict", $utf8_contents, Encode::FB_CROAK )
            ;                  # ensure it's really valid UTF-8 or croak
            croak("Invalid control characters in file $utf8_file")
            if $decoded_utf8 =~ /[\x00-\x08\x0B-\x1F]/m;
            close($utf8_fh);
        };
        if ($@) {
            $self->set_error(
                "BadUTF",
                field  => 'utf8',
                detail => "$@",
                file   => $utf8_file
            );
        }

    }
}
```

**Comment by grosscol** [comment]
That seems like a reasonable approach.  Whatever the current utf-8 decoder barfs on we're taking as bad utf-8.  Some of the byte strings in the utf-8 test cases above should provide sufficient fixtures for the spec.
