### ISSUE TITLE
Use validation in shared examples

### ISSUE THREAD

**Issue by grosscol** [hathitrust/ht_sip_validator#53]
Per discussion in #35, use 'validation' instead of 'validator' in shared examples.
Refactor existing validation specs.

**Comment by grosscol** [comment]
Specifically:
"validation" should be used when working with HathiTrust::Validation::Base
"validator" should be used when working with HathiTrust::Validation::SIPValidator

**Comment by aelkiss** [comment]
Should we move HathiTrust::Validation::SIPValidator to HathiTrust::SIPValidator?
