### ISSUE TITLE
Refactor Messages fields

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#69]
- Create a controlled vocabulary for what we currently call 'validation'
- Figure out something better to call the field we currently call `validation` - maybe `validation_type`?
- That should map to an expected set of fields in `extra`
- Call `field` target instead (since it could be a directory rather than a field)
- Log the class of the whatever created the messages.

**Comment by aelkiss** [comment]
Partially addressed by #67

**Comment by malakai97** [comment]
### Re: Controlled vocabulary
These are the types of things we're doing now:

- existence of files/folders
- existence of fields
- pairwise presence of fields
- presence of extra files/folders
- presence of extra fields
- checksum mismatch
- format of field values
- format of files?

This list isn't too bad but I feel like the edges of each of these are fuzzy enough that proper categorization might be a daunting task.  

### Name for the `validation` field
`validation_type` is fine by me.

### Message class
Adding storing what created the messages, the new name for `:validation`, and `filename -> target`, we get:
```
Message.new(
  validator: self.class.to_s,
  validation_type: :field_valid,
  level: Message::ERROR,
  human_message: "some_message",
  extras: {
    filename: "meta.yml",
    field: "pagedata",
    actual: key
  }
)
```

**Comment by aelkiss** [comment]
Here is a relevant list of error types from the existing validator. I'm not sure all of these are in use, some are duplicative, some are highly overused - definitely should not use this list as is, but it would be good to make sure we at least cover the same space:

```perl
my %error_codes = (
    BadChecksum         => 'Checksum error',
    BadField            => 'Error extracting field',
    BadFile             => 'File validation failed',
    BadFilegroup        => 'File group empty or contains too many items',
    BadFilename         => 'Invalid filename',
    BadUTF              => 'UTF-8 validation error',
    BadValue            => 'Invalid value for field',
    OperationFailed     => 'Operation failed',
    FatalError          => 'Fatal error',
    MissingField        => 'Missing field value',
    MissingFile         => 'Missing file',
    NotEqualValues      => 'Mismatched field values',
    NotMatchedValue     => 'Mismatched/invalid value for field',
    UnexpectedError     => 'Unexpected error', 
);
```

**Comment by aelkiss** [comment]
Here is the set of `validation_type` symbols currently in the code base:

```ruby
[:has_field, 
:field_valid, 
:field_presence,
:file_present,
:exists,
:well_formed,
:file_list_complete,
:image_filename,
:image_sequence,
:image_count]
```

Let's change:
- `:has_field` -> `:field_presence`
- `:file_present` -> `:file_presence`
- `:exists` -> `:file_presence` (this is in `Checksums::Exists`, `MetaYml::Exists`
- `:well_formed` -> `:file_well_formed` (This will be useful for image validation as well. If it's checking well-formedness of an individual field, I think `:field_valid` is probably fine. I don't think we need to nitpick the difference between well-formedness and validity of individual fields, nor are we likely to have validators that operate at that level of detail. On the other hand we already have file-level well-formedness checks and are likely to have more, and we are NOT likely to have whole-file validity checks at a level captured by an individual message)
- `:image_count` -> `:file_presence` - it's checking if there is a text file for every image file
- `:image_sequence` in `no_images_error`, `missing_error_for` -> `:file_presence`
- `:image_sequence` in `invalid_error_for` -> `:filename_valid` (NEW)

I'm not sure about:

- `:file_list_complete` -> `:field_presence`, maybe? It's checking that the checksum list is complete. If we think about an individual entry in `checksum.md5` as being a field, then `:field_presence` makes sense... 
- `:image_sequence` in `duplication_error_for` -> maybe `:filename_valid`? A duplicate is a valid image filename though, just duplicated.. maybe worth making a new category for? I'm not sure this kind of thing will really come up anywhere else.

**Comment by aelkiss** [comment]
For consistency I think I actually want `present` instead of `presence`. I think these should be in the form of checking if the BLANK is BLANK, e.g. if the "field" is "valid" or the "file" is "well-formed".

- #38 : `:field_valid`
- #36 : Actually this is another instance of something checking for duplication. So maybe use `:filename_unique` for this and in `duplication_error_for`?
- #23 : `:file_present`
- #22 : `:file_present` (actually already done in #66)
- #20 : `:file_well_formed`
- #19 : `:file_well_formed`
- #18 : Need something new for checking that the file checksum matches checksum.md5. The spirit of this is more as a check on the file than on `checksum.md5` - if they mismatch we don't know which is wrong, but we're really interested in the check because it's checking something about the file. So maybe `:file_intact` or `:file_checksum_valid`?
- #15 : `:file_presence`, maybe? This is checking for extra files, though. We should probably use the same thing here and for the things that are checking for duplicate files/sequences, but I'm having trouble coming up with a good name. Something like `:file_extraneous` maybe?
- #14 : `:filename_valid`
- #13 : `:filename_valid`

**Comment by aelkiss** [comment]
Migrated to HTREPO-147
