### ISSUE TITLE
test whatever we use for zips with zip64

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#70]

**Comment by aelkiss** [comment]
>4G zips have some issues sometimes

**Comment by grosscol** [comment]
I can take a stab at this.  I have some idea about how to test this.
* Generate a fixture that lies about it's size and claims to be 8gb.  Extract a single file from that.  That would also illuminate if or how a reported vs actual size mismatch is handled.
* Generate a 4.5G zip file on the fly.  Not a test to run often.

**Comment by aelkiss** [comment]
I've encountered some very rare issues with ZIP64 and rubyzip, but in general we know it works from datasets.
