### ISSUE TITLE
Use mock class instead of actual Ruby class in message spec when spec intent is "any appropriate class"

### ISSUE THREAD

**Issue by grosscol** [hathitrust/ht_sip_validator#75]
https://github.com/hathitrust/ht_sip_validator/blob/master/spec/validation/message_spec.rb#L28-L29

This is demonstrating that the validator method accepts a class as an argument. I would use a mock class instead of an actual Ruby class in order to avoid implying that one should actually pass in an Integer in code. Some people refer back to specs to see analogs of expected usage. If the class isn't explicitly a mock class, a reader (possibly a future me) might not immediately grok that Integer is supposed to be something more appropriate in actual usage.

**Comment by aelkiss** [comment]
Migrated to HTREPO-146
