### ISSUE TITLE
consider removing behaviors from `HathiTrust::SIP::SIP`

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#83]
Inspired by https://www.destroyallsoftware.com/talks/boundaries

HathiTrust::SIP::SIP might be a good candidate for making purely functional, since the actual content of the SIP doesn't change throughout the validation process, and all the validators are already purely functional (they are stateless and just take a SIP and return some messages)

By changing `HathiTrust::SIP::SIP` to hold only data and creating a new `HathiTrust::SIP::SIPReader` that actually reads the data from the filesystem, we could make several improvements: 

- Would allow us to eliminate SIP mocking in most cases
- Would allow us to parallelize validators (that would also require real dependency resolution, but that isn't too hairy)

**Comment by grosscol** [comment]
So totally encapsulating the I/O operations into a class?  That sounds like a good idea.  It would simplify the SIP specs and contract.  Also pushes the fail prone bits further from the business logic.

**Comment by grosscol** [comment]
By the boundaries method, should also have a ```HathiTrust::SIP::MessageWriter``` that takes care of taking the messages and printing them to the screen, or logger, or database or whatever.

**Comment by aelkiss** [comment]
Migrated to HTREPO-145
